#!/usr/bin/sh

#  Use the ntop development SPEC files to build PF_RING, ntopng and ntopng-data packages

set -e   #  Terminate on error

export HOME="/tmp/ntopng-build"
rm -fr $HOME || true
mkdir ${HOME}

cd ${HOME}
rpmdev-setuptree

#  DOES NOT WORK - Reported PF_RING compile bugs with kernel 6.6.9
#git clone https://github.com/ntop/PF_RING.git
#cd PF_RING
#make
#cd ..
#VERSION=$(cat PF_RING/package/rpm/pfring.spec | grep ^Version: | awk '{print $2}')
#tar -cvzf ${HOME}/rpmbuild/SOURCES/PF_RING-${VERSION}.tgz PF_RING
#
#cp PF_RING/package/rpm/pfring.spec ${HOME}/rpmbuild/SPECS/
#rpmbuild -ba ${HOME}/rpmbuild/SPECS/pfring.spec

git clone https://github.com/ntop/nDPI.git
cd nDPI
./autogen.sh
make
cd ..

git clone https://github.com/ntop/ntopng.git
cd ntopng
./autogen.sh
./configure
make
cd ..
VERSION=$(cat ntopng/packages/ntopng.spec | grep ^Version: | awk '{print $2}')
tar -cvzf ${HOME}/rpmbuild/SOURCES/ntopng-${VERSION}.tgz ntopng nDPI

mkdir dat_files
cd dat_files
wget https://download.db-ip.com/free/dbip-country-lite-$(date +%Y-%m).mmdb.gz
wget https://download.db-ip.com/free/dbip-city-lite-$(date +%Y-%m).mmdb.gz
wget https://download.db-ip.com/free/dbip-asn-lite-$(date +%Y-%m).mmdb.gz
gunzip *.gz
cd ..
tar -cvzf ${HOME}/rpmbuild/SOURCES/ntopng-data-${VERSION}.tgz dat_files

cp ntopng/packages/ntopng.spec ${HOME}/rpmbuild/SPECS/
rpmbuild -ba ${HOME}/rpmbuild/SPECS/ntopng.spec

cp ntopng/packages/ntopng-data.spec ${HOME}/rpmbuild/SPECS/
rpmbuild -ba ${HOME}/rpmbuild/SPECS/ntopng-data.spec
